### ISSUE TITLE
What does the '-BLK' mean?

### ISSUE THREAD

**Issue by ljk628** [sixin-zh/mpiT#3]
Hi Sixin, 

Thanks for your sharing of this package! I am working on to improve this package.  I have a few questions during reading the code:
1. Is the 'asyncsgd' folder an implementation of your Elastic Averaging SGD paper?
2. What does the short comment of '--BLK' mean in goot.lua?

There are some minor mistakes that could be fixed to make it working:
1. goot.lua: confusion:addbatch --> confusion:BatchAdd
2. plaunch.lua: "require 'mpiT'" should appear before dofile('init.lua')

Thanks,
Hao

**Comment by sixin-zh** [comment]
Thanks for the advice. If you plan to run the asyncsgd code, you might want
to patch your Torch with the following.
This api is exposed to increase the efficiency of the communication, and
it's simple to integrate with mpiT.
But you need to pay attention to the garbage collection when using this.

---

_# torch7_
torch7/lib/TH/generic/_THStorage.c_
THStorage\* THStorage_(newWithOffset)(real *data, long offset, long size)
{
  THStorage *storage = THAlloc(sizeof(THStorage));
  storage->data = data+offset;
  storage->size = size;
  storage->refcount = 0;
  storage->flag = TH_STORAGE_FREEMEM; // shadow data
  return storage;
}

torch7/lib/TH/generic/_THStorage.h_
TH_API THStorage\* THStorage_(newWithOffset)(real *data, long offset, long
size);

_# cutorch_
../torch/extra/cuda/lib/THC/_THCStorage.c_:
THCudaStorage\* THCudaStorage_newWithOffset(
float *data, long offset, long size)
{
  THCudaStorage *storage = THAlloc(sizeof(THCudaStorage));
  storage->data = data+offset;
  storage->size = size;
  storage->refcount = 0;
  storage->flag = TH_STORAGE_FREEMEM; // shadow data
  return storage;
}

_# torch7 & cutorch_torch7/generic/_Storage.c:_
cutorch/torch/generic/_Storage.c_:
  else if (lua_type(L, 1) == LUA_TUSERDATA)
    {
      // new with offset, just reference, no mem
alloc

```
  // src,dest same type assumed, need
```

check

```
  storage = luaT_checkudata(L, 1, torch_Storage);
  long offset = luaL_checklong(L, 2);
  long size = luaL_checklong(L, 3);
  storage = THStorage_(newWithOffset)(storage->data,offset,size);
}
```
