### ISSUE TITLE
seg fault in Allreduce.  How to fix?

### ISSUE THREAD

**Issue by hughperkins** [sixin-zh/mpiT#5]
Hi,  I love using mpi, and I'm excited that mpi is available for torch.  I'm trying to do a simple Allreduce, and it segfaults.  Thoughts?  Basically ,I copied test.lua to testreduceall.lua, and added th efollowing lines just before the `mpiT.Finalise()`:

```
torch.manualSeed(123)
a = torch.FloatTensor(3,2):uniform()
print('a', a)
mpiT.Allreduce(a:storage(), 6, mpiT.FLOAT, mpiT.SUM, mpiT.COMM_WORLD)
print('a after', a)
```

I'm running like:

```
mpirun.mpich -np 4 luajit testreduceall.lua
```

What I expect to happen:
- some sort of mangled print out of initial a tensors
- some sort of mangled print out of a tensors multiplied by 4

What actually happens:

```
$ mpirun.mpich -np 4 luajit testreduceall.lua 
init
init
init
initsize
size
size
[0/4]s=0r=0
[2/4]s=2r=2

size
[3/4]s=3r=3[1/4]s=1r=1

[1/4]s=1r=0
[2/4]s=2r=1
[3/4]s=3r=2[0/4]s=0r=3

aaaa     0.6965  0.7130
 0.2861  0.4285
 0.2269  0.6909
[torch.FloatTensor of size 3x2]

     0.6965  0.7130
 0.2861  0.4285
 0.2269  0.6909
[torch.FloatTensor of size 3x2]

     0.6965  0.7130
 0.2861  0.4285
 0.2269  0.6909
[torch.FloatTensor of size 3x2]

     0.6965  0.7130
 0.2861  0.4285
 0.2269  0.6909
[torch.FloatTensor of size 3x2]


===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   EXIT CODE: 11
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
```

**Comment by hughperkins** [comment]
Oh wait, I should be sending two tensors right (one for receive, one for send).  => closing.

**Comment by hughperkins** [comment]
(Yay, works :-) )

```
mpiT.Allreduce(a:storage(), a_reduced:storage(), 6, mpiT.FLOAT, mpiT.SUM, mpiT.COMM_WORLD)
```

**Comment by sixin-zh** [comment]
Thanks for trying allreduce. The API is defined in
https://github.com/sixin-zh/mpiT/blob/master/specs/allreduce.json
the json is then parsed by
https://github.com/sixin-zh/mpiT/blob/master/readspec.py to generate the c
code.

**Comment by hughperkins** [comment]
"to generate the c code"

Ummmm.... you mean.... when I call this function, it's going to generate c code? :-P

**Comment by hughperkins** [comment]
Oh, you mean, you run `python readspec.py >mpifuncs.c`, and this generates the mpifuncs.c, that is compiled during the `luarocks make`?

**Comment by sixin-zh** [comment]
correct.

**Comment by hughperkins** [comment]
Ah :-)  Cool :-)  That sounds like a really good way of doing it :-)

**Comment by sixin-zh** [comment]
it can be regenerated if you rerun the .py file.

**Comment by sixin-zh** [comment]
this is done actually by lua-mpi: https://github.com/jzrake/lua-mpi

**Comment by hughperkins** [comment]
Ok
